### ISSUE TITLE
Unable to close shape - 'Draw Area' - 'free draw'

### ISSUE THREAD

**Issue by greytilde** [WikiWatershed/model-my-watershed#1190] opened 2016-03-14 00:57 UTC
Creating a simple 4 sided shape,   when clicking back on the first corner, the shape would not close. Click radius might be too small. No amount of clicking would cause the shape to close. Only additional points were created (see screen shot)
<img width="960" alt="unable to close shape - free draw" src="https://cloud.githubusercontent.com/assets/8659605/13732665/1394bc30-e95e-11e5-8cde-0f9945649998.png">

**Comment by rajadain** [comment] 2016-03-14 12:07
Duplicate of #649. Also see #892 (closed).

**Comment by SRGDamia1** [comment] 2016-03-15 15:52
We confirmed that this is a problem on a Surface 4 running Windows 10.

I was also looking over the series of these issues wrt touch on leaflet draw and found that the newest release of leaflet.draw (0.3.0, released March 9, 2016) is now supposed to support touch devices: https://github.com/Leaflet/Leaflet.draw/blob/master/CHANGELOG.md#030-march-09-2016

**Comment by rcheetham** [comment] 2016-05-27 18:28
I noticed the same thing in Chrome 50 on Windows 10. I do think it's likely a scale dependent issue. The cursor changes when you are over the vertex (in other words, the ability to detect cursor location intersection with the vertex seems to be fine), but I was only able to successfully close a shape perhaps 1 in 4 times.

**Comment by SRGDamia1** [comment] 2016-06-16 14:48
I just got another email of someone reporting the same bug.

**Comment by rajadain** [comment] 2016-08-15 20:14
I just put up #1421 to upgrade Leaflet.Draw to 0.3.0, but that doesn't fix the issues in Chrome and Firefox unfortunately. IE and Edge now work correctly though, which may hold our Windows users over for a bit. See #649 (comment) for details.

**Comment by arottersman** [comment] 2016-09-06 15:22
I was able to fix the issue for Chrome and Firefox on Windows by forking `Leaflet.Draw` and updating how the library handles its touch events: https://github.com/arottersman/Leaflet.draw 

Any thoughts on the best way to incorporate the update into Model My Watershed if we don't want to wait for `Leaflet.draw` proper to accept a PR of my change?

**Comment by mmcfarland** [comment] 2016-09-06 18:09
I think the best way to move forward on this is to create a PR which points the MMW project to a branch on your `L.Draw` fork, which we could then go about testing.  I'm curious, for instance, to see if your changes are compatible with a touch-only device like an iPad.

We used a leaflet draw fork for a while and only recently switched back when they incorporated some draw fixes - we can switch to a new fork again for the app and work through getting a PR accepted to the main project.

**Comment by rajadain** [comment] 2016-09-06 18:13
On that note, there is also an official Azavea fork of Leaflet.draw https://github.com/azavea/Leaflet.draw, which has [some new work](https://github.com/azavea/Leaflet.draw/commit/c05b18cf1aef5b954e9f1fe5be819bc3691849cb) that while accepted into https://github.com/michaelguild13/Leaflet.draw never made it in to https://github.com/Leaflet/Leaflet.draw. I'm not sure how best to test it, but it is possible for us to incorporate both in to the Azavea fork and use that instead of @arottersman's.

**Closed** 2016-09-08 19:48 UTC
Labels: OSI
