### ISSUE TITLE
How should we handle an error in the analyze process?

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#818] opened 2015-09-21 15:29 UTC
Currently, if there is an error in the analyze process which results in an empty census, we let the user proceed to the modeling page. The modeling results will always come back with invalid results in this case (mostly with `0`'s for every value).

We currently show a simple error message when the analyze task fails, but 

Should we prevent the user from proceeding to the modeling page? How should this be reflected in the UI?

**Comment by caseypt** [comment] 2015-09-21 15:30
Perhaps the button to the modeling page shouldn't appear until the analyze tasks succeeds.

**Comment by caseypt** [comment] 2015-09-21 17:27
This is what app currently looks like when there is an error on the analyze page. Note that the modeling button is still active.

![screen shot 2015-09-21 at 1 27 52 pm](https://cloud.githubusercontent.com/assets/1042475/9999460/87a57c46-6064-11e5-90ca-9be1925ecb3f.png)

**Comment by mmcfarland** [comment] 2015-09-21 17:55
I think we should have text and a button in the error output that says something along the lines of "Unable to compute the [land use] analysis, click here to try again" which would submit the job again.  In some cases, the user might not actually care.  

I'm not sure if the model should be unavailable when the analysis fails since the data (at the moment) isn't connected at all.  It's entirely likely that if there were errors due to the size of the AoI the model results will also fail, but if there is a bug or hiccup in the analysis, that wouldn't _necessarily_ compromise the model results.

**Comment by caseypt** [comment] 2016-11-02 13:46
Although the design has changed since this issue has been created, this is still reproducible.

**Comment by ajrobbins** [comment] 2017-08-18 19:34
>I'm not sure if the model should be unavailable when the analysis fails since the data (at the moment) isn't connected at all. It's entirely likely that if there were errors due to the size of the AoI the model results will also fail, but if there is a bug or hiccup in the analysis, that wouldn't necessarily compromise the model results.

Agreed with this. Since it's a question and not a task, closing.

**Closed by ajrobbins** 2017-08-18 19:34 UTC
Labels: question

**Comment by caseycesari** [comment] 2017-08-18 19:50
Sounds good. For the record, I still think it is odd that the app has what looks like a three-step process (1. select an AoI, 2. analyze, 3. model), but if step 2 fails the user can still proceed to step 3.

> but if there is a bug or hiccup in the analysis, that wouldn't necessarily compromise the model results.

I think we should add a retry button for hiccups, and try to fix any analyze bugs.
