### ISSUE TITLE
RWD Feedback

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1658] opened 2017-01-12 19:29 UTC
* Help debug RWD issues on staging
* Rename mid-atlantic RWD region
This should probably read "National Medium Resolution" and be the first in the list.

![screenshot 2017-01-12 at 2 28 00 pm](https://cloud.githubusercontent.com/assets/1014341/21904947/7d0c57bc-d8d3-11e6-96ab-2e13d98801b5.png)

@SRGDamia1 or @aufdenkampe, do you have input into what the best label for National RWD is (to replace Mid-Atlantic)?

**Comment by aufdenkampe** [comment] 2017-01-13 17:55
In his 12/3/2016 email response to the "MMW Release 1.17" thread, @dtarb suggested this:

> I suggest the following wording:
>  
> In the overlay labels
> -          Delaware high resolution stream network
> -          Continental US medium resolution stream network
>  
> In the delineate watershed tool
> -          Snap to Delaware high resolution streams
> -          Snap to Continental US medium resolution streams
>  
> In the help text
> This moves downhill from the point you click to snap onto the nearest point on the Delaware high resolution stream network and calculates the watershed upstream of this point using a 1/3 arc second (10) m resolution digital elevation model for the Delaware River Basin.  The stream network snapped to was delineated using TauDEM (http://hydrology.usu.edu/taudem).
>  
> This moves downhill from the point you click to snap onto the nearest point on the medium resolution National Hydrography Dataset (NHDPlus flowline) and calculates the watershed upstream of this point using the 30 m resolution NHDPlus flow direction grid for the continental US.  If the point you click does not have a NHDPlus flowline downstream of it (e.g. is in an internally draining area) the watershed is calculated from the point you click.  Watersheds calculated may have holes in them due to internally draining areas that do not connect to the outlet in the NHDPlus flow direction dataset.  To learn more about NHDPlus see  http://www.horizon-systems.com/nhdplus/.  The model my watershed watershed delineation uses NHDPlus version 2.1 data model with latest content version accessed 11/22/16.
>  
> Rationale
> I tried to be precise as well as simple in the wording, but welcome improvements.  It seemed incorrect to refer to NHD stream and flow data as streamflow data is not actually used.  Also, the tool does not delineate a stream network, it delineates a watershed from a point on the stream network.  In the help I have defined what we mean when we say high or medium resolution.  This terminology is somewhat consistent with USGS use.  They refer to the NHD resolution that NHDPlus uses and that we used as “medium resolution”.  They have their own High Resolution NHD dataset, but we have not used this.  We developed our own dataset for the Delaware that is even higher resolution than NHD high resolution.  If you want to shorten the help text, some of the sentences at the end could be dropped, but it seems that this information needs to be somewhere.  It may be necessary to link to more detailed documentation on the datasets that is more extensive (and still to be written) instead of extending the help too much.
>  
> I used the word “Continental US” in anticipation that the recently completed Lower 48 states rapid watershed delineation dataset will be deployed.  If the deployment is limited to region 2, the term “Mid-Atlantic region” should be used.  The “Continental” dataset does not include Alaska.  The word “Contiguous” is sometimes used, or “Lower 48 states”, but “Continental” seems simpler to me.  There is no NHDPlus raster data available for Alaska, but if you want a RWD dataset for Alaska, I could develop one using raw DEM data.  Also left out of the Continental US dataset are Hawaii (Region 20), Peurto Rico (region 21), American Samoa, Guam and Northern Mariana Islands (Region 22).  There is NHDPlus raster data available for these, and RWD content could be developed for them if you want.

**Comment by aufdenkampe** [comment] 2017-01-13 18:09
I now see that most of the input @dtarb's email, above, pertains to the request from @ajrobbins for Help text and in response to @SRGDamia1's suggestion.  I see that @dtarb's suggestion was condensed and incorporated (thank you).

I like @dtarb's suggestion for "Snap to Continental US medium resolution streams", and for that to be first on the list. If it needs to be shorter, I would shorten to "Snap to US medium resolution streams".

Likewise, second on the list should be "Snap to Delaware high resolution streams", which if it has to be shorter, could be "Snap to DRB high resolution streams". I realize that we want to get away from acronyms, but I also feel that "Snap to" is very important to distinguish this function from functionality of the Overlays menu. I also very much appreciate @dtarb's effort to otherwise keep the wording of "Delineate..." options as similar as possible to the "Overlays" options, to make the connection between the two as clear as possible.

**Comment by ajrobbins** [comment] 2017-01-13 20:20
For the renaming portion of this task:

In the Delineate watershed dropdown - 
`Mid-Atlantic Medium Resolution` --> `Continental U.S. Medium Resolution`

**Comment by aufdenkampe** [comment] 2017-01-13 20:36
@ajrobbins, What about:

`Mid-Atlantic Medium Resolution` --> `Snap to Continental U.S. Medium Resolution`
or 
`Mid-Atlantic Medium Resolution` --> `Snap to U.S. Medium Resolution`

**Comment by dtarb** [comment] 2017-01-14 01:25
There are locations where RWD on staging appears not to connect to upstream watersheds.  One such location is (longitude, latitude) =(-89.634413  36.244647).

Following is what RWD produces
![image](https://cloud.githubusercontent.com/assets/3456833/21950962/72434d00-d9bd-11e6-845a-580f19613048.png)

Following is what testing on my RWD development environment produces.
![image](https://cloud.githubusercontent.com/assets/3456833/21950969/7c79b890-d9bd-11e6-9874-a77363911caf.png)
![image](https://cloud.githubusercontent.com/assets/3456833/21950971/84422846-d9bd-11e6-811c-b594612e9ef6.png)


We need to figure out why the catchment upstream is not being merged in

**Comment by ajrobbins** [comment] 2017-01-15 18:07
@aufdenkampe My thought was that the "snap to" language isn't immediately understandable for folks not familiar with the methodology, and would be better saved for the help text that appears when you hover over the info icon. If you think most people using that feature will grasp the "snapping" concept, though, that could work.

**Comment by mmcfarland** [comment] 2017-01-16 15:11
@dtarb What would be a good step towards debugging that issue, or what might be the most likely cause?  Could we be missing some sub-directories of data?  We can also add some logging to particular methods if the output would help us narrow in on the issue.

**Comment by aufdenkampe** [comment] 2017-01-16 16:21
@dtarb, ​I noticed the same behaviors. Thanks for documenting all this, and working out a fix as posted at https://github.com/WikiWatershed/rapid-watershed-delineation/issues/53

**Comment by aufdenkampe** [comment] 2017-01-16 16:26
@ajrobbins, OK. I think your suggestion makes sense, especially given that you also left out the word "streams". Selecting "Delineate Watershed > Continental U.S. Medium Resolution" is sufficiently different from selecting "Overlays > Continental U.S. Medium Resolution Stream Network"

**Comment by dtarb** [comment] 2017-01-16 17:54
@aufdenkampe my changes in https://github.com/WikiWatershed/rapid-watershed-delineation/issues/53 do not address this as I do not know what is causing the behavior.  It is working correctly in my testing system.

@mmcfarland to debug I suggest deleting/commenting out the lines purge(path, pattern) and os.remove('upwacoor.txt') near the end of NHD_Rapid_Watershed_Delineation.py then lets look at the contents of upwacoor.txt and other files in this folder to try figure this out.

I just tried on the site a few minutes ago, and am unable to reproduce the error.  I get the "Unable to delineate watershed at this location" error, which I interpret to be "Too big".

Has the site been updated?

**Comment by dtarb** [comment] 2017-01-16 18:20
With respect to the "snap to" words I agree with leaving them out in the initial labels and going with what we seem to have converged upon.  
Delineate Watershed > Delaware High Resolution
and
Delineate Watershed > Continental US medium resolution

I think that the explanations in the text that appears when one hovers over ? are sufficient to explain the snap to and simple concepts of the watershed delineation.

I have noticed that I have trouble getting the hover over text to display.  It displays when I first go to a site, but after I have attempted to delineate a watershed and received an error (say for watershed too big), even after a reset the text does not display and I seem to have to close and reopen the browser for it to display.

**Comment by ajrobbins** [comment] 2017-01-16 18:31
Thanks for reporting that @dtarb - haven't noticed it myself but I'll do some testing and try to replicate, and create a spinoff github issue.

**Comment by kdeloach** [comment] 2017-01-16 23:05
> There are locations where RWD on staging appears not to connect to upstream watersheds.  One such location is (longitude, latitude) =(-89.634413  36.244647).

> Following is what RWD produces
![image](https://cloud.githubusercontent.com/assets/3456833/21950962/72434d00-d9bd-11e6-845a-580f19613048.png)

I was able to reproduce this error. From the logs:

```
MoveOutletsToStreams version 5.3.8
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371src1.tif has projected coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif has projected coordinate system.
New_Outlet Total time: 0.818825
Gage Watershed version 5.3.8
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif has projected coordinate system.
Warning: Projection of Outlet feature and Raster data may be different.
Projection of Raster datasource unnamed.
Projection of Outlet feature Albers.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Size: 1
Read time: 0.578064
Compute time: 0.099530
Write time: 0.106063
Total time: 0.783657
Creating output local_subwatershed.shp of format ESRI Shapefile.
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 1: Not enough memory to allocate requested memory (nPoints=0, nParts=3098667) for shape 1. Probably broken SHP file
```

This could be due to data corruption. I'll re-download the archive for this subwatershed to see if that has any impact.

**Comment by kdeloach** [comment] 2017-01-16 23:34
Here are the MD5 checksums for the NHD archives in production. This does not include the data updates which fix internally draining gaps.

[checksums.txt](https://github.com/WikiWatershed/model-my-watershed/files/709634/checksums.txt)

**Comment by dtarb** [comment] 2017-01-17 00:23
I do not know how to generate checksums to compare.  Also, these seem to be for zip files.  If the zip file is corrupt it should tell you on unzipping.

The problem is occurring between lines 131 and 204 of the code (looking at code in develop branch at https://github.com/WikiWatershed/rapid-watershed-delineation/blob/develop/rwd_nhd/NHD_Rapid_Watershed_Delineation.py)

I am most suspicious of the code at line 196.  What does the print at line 195 tell us.  It does not appear to be in the log sent.  It should be your equivalent of the following on my system

'ogr2ogr -update -append E:\\NHDPlus\\RWDData\\Main_Watershed\\dw\\local_subwatershed_dissolve.shp E:\\NHDPlus\\RWDData\\Subwatershed_ALL\\Subwatershed31372\\Simple_watershed31372.shp'

This is appending the upstream Simple_watershed31372.shp onto the local subwatershed. The file being appended is 48 MB. This was provided at part of the Simple.zip file.  If you instruct me I could validate its checksum.  I am also downloading it and will check this watershed in the version I download. 

Another possible problem is line 203.  This dissolves the geometry of the combined shapefile and writes it to New_Point_Watershed.shp.

Check what was printed at line 202.

The code could go further wrong in adding watershed attributes in the call at line 215, but I think if this was the case we would see the big shapefile in the result.

If/when you download the archive check the shapefile \\Subwatershed_ALL\\Subwatershed31372\\Simple_watershed31372.shp  (linux path equiv of this).  See if it looks like the Mississippi basin upstream of this point.

Also consider commenting out the clean up code at lines 230 and 231 then looking at the files in the directory after this run.

**Comment by kdeloach** [comment] 2017-01-17 00:29
More detailed log:

```
31371
search 0.545493841171 seconds ---
"/usr/local/bin/mpiexec"  "--allow-run-as-root"  "-np"  "1"  "/opt/taudem/moveoutletstostrm"  "-p"  "/opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif"  "-src"  "/opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371src1.tif"  "-o"  "/tmp/tmph2MgmY/mypoint.shp"  "-om"  "/tmp/tmph2MgmY/New_Outlet.shp"  "-md"  "343" 
MoveOutletsToStreams version 5.3.8
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371src1.tif has projected coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif has projected coordinate system.
New_Outlet Total time: 0.286265
"/usr/local/bin/mpiexec" "--allow-run-as-root" "-np" "1" "/opt/taudem/gagewatershed" "-p" "/opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif" "-o" "/tmp/tmph2MgmY/New_Outlet.shp" "-gw" "/tmp/tmph2MgmY/local_subwatershed.tif" "-id" "/tmp/tmph2MgmY/local_subwatershed.txt" "-upid" "/tmp/tmph2MgmY/upwacoor.txt" 
Gage Watershed version 5.3.8
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif has projected coordinate system.
Warning: Projection of Outlet feature and Raster data may be different.
Projection of Raster datasource unnamed.
Projection of Outlet feature Albers.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Size: 1
Read time: 0.286504
Compute time: 0.033210
Write time: 0.013412
Total time: 0.333126
gdal_polygonize.py -8 local_subwatershed.tif -b 1 -f "ESRI Shapefile" local_subwatershed.shp local_subwatershed GRIDCODE
Creating output local_subwatershed.shp of format ESRI Shapefile.
0...10...20...30...40...50...60...70...80...90...100 - done.
ogr2ogr local_subwatershed_dissolve.shp local_subwatershed.shp -dialect sqlite -sql "SELECT GRIDCODE, ST_Union(geometry) as geometry FROM local_subwatershed GROUP BY GRIDCODE" -nln results -overwrite
Identify upstream watershed 0.12753200531 seconds ---
Up stream edge was reached
ogr2ogr -update -append /tmp/tmph2MgmY/local_subwatershed_dissolve.shp /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31372/Simple_watershed31372.shp
ogr2ogr New_Point_Watershed.shp local_subwatershed_dissolve.shp -dialect sqlite -sql "SELECT GRIDCODE, ST_Union(geometry) as geometry FROM local_subwatershed_dissolve"
GEOS error: std::bad_alloc
Error running Point_Watershed_Function
Traceback (most recent call last):
  File "main.py", line 123, in run_rwd_nhd
    output_path,
  File "/opt/rwd/rwd_nhd/NHD_Rapid_Watershed_Delineation.py", line 223, in Point_Watershed_Function
    output_dir)
  File "/opt/rwd/rwd_nhd/NHD_RWD_Utilities.py", line 248, in get_watershed_attributes
    layer = source.GetLayer()
AttributeError: 'NoneType' object has no attribute 'GetLayer'
```

**Comment by kdeloach** [comment] 2017-01-17 00:39
Sometimes the RWD code will finish without a problem, but still fail to generate JSON.

Example:

```
31371
search 0.652953147888 seconds ---
"/usr/local/bin/mpiexec"  "--allow-run-as-root"  "-np"  "1"  "/opt/taudem/moveoutletstostrm"  "-p"  "/opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif"  "-src"  "/opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371src1.tif"  "-o"  "/tmp/tmpeGUQM4/mypoint.shp"  "-om"  "/tmp/tmpeGUQM4/New_Outlet.shp"  "-md"  "343"
MoveOutletsToStreams version 5.3.8
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371src1.tif has projected coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate.
Run time is highly uncertain as it depends on the complexity of the input data
and speed and memory of the computer. This estimate is based on our testing on
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif has projected coordinate system.
New_Outlet Total time: 0.340421
"/usr/local/bin/mpiexec" "--allow-run-as-root" "-np" "1" "/opt/taudem/gagewatershed" "-p" "/opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif" "-o" "/tmp/tmpeGUQM4/New_Outlet.shp" "-gw" "/tmp/tmpeGUQM4/local_subwatershed.tif" "-id" "/tmp/tmpeGUQM4/local_subwatershed.txt" "-upid" "/tmp/tmpeGUQM4/upwacoor.txt"
Gage Watershed version 5.3.8
Input file /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31371/subwatershed_31371p.tif has projected coordinate system.
Warning: Projection of Outlet feature and Raster data may be different.
Projection of Raster datasource unnamed.
Projection of Outlet feature Albers.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate.
Run time is highly uncertain as it depends on the complexity of the input data
and speed and memory of the computer. This estimate is based on our testing on
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Size: 1
Read time: 0.331541
Compute time: 0.027332
Write time: 0.012483
Total time: 0.371356
gdal_polygonize.py -8 local_subwatershed.tif -b 1 -f "ESRI Shapefile" local_subwatershed.shp local_subwatershed GRIDCODE
Creating output local_subwatershed.shp of format ESRI Shapefile.
0...10...20...30...40...50...60...70...80...90...100 - done.
ogr2ogr local_subwatershed_dissolve.shp local_subwatershed.shp -dialect sqlite -sql "SELECT GRIDCODE, ST_Union(geometry) as geometry FROM local_subwatershed GROUP BY GRIDCODE" -nln results -overwrite
Identify upstream watershed 0.150209903717 seconds ---
Up stream edge was reached
ogr2ogr -update -append /tmp/tmpeGUQM4/local_subwatershed_dissolve.shp /opt/rwd-data/nhd/Subwatershed_ALL/Subwatershed31372/Simple_watershed31372.shp
ogr2ogr New_Point_Watershed.shp local_subwatershed_dissolve.shp -dialect sqlite -sql "SELECT GRIDCODE, ST_Union(geometry) as geometry FROM local_subwatershed_dissolve"
writing  time 0.31428694725 seconds ---
watershed attributes time 11.4728748798 seconds ---
Error running Point_Watershed_Function
Traceback (most recent call last):
  File "main.py", line 138, in run_rwd_nhd
    from_epsg=5070, to_epsg=4326),
  File "main.py", line 173, in load_json
    output = json.load(output_json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

In this case, the value of upwacoor.txt was:

```
root@499f80f0fedd:/tmp/tmpeGUQM4# cat upwacoor.txt
572700.000000, 1488990.000000
572670.000000, 1488990.000000
572640.000000, 1488990.000000
572640.000000, 1488990.000000
572610.000000, 1488990.000000
572580.000000, 1488990.000000
572730.000000, 1488990.000000
572700.000000, 1488990.000000
572670.000000, 1488990.000000
572670.000000, 1488990.000000
572640.000000, 1488990.000000
572610.000000, 1488990.000000
572610.000000, 1488990.000000
572580.000000, 1488990.000000
572550.000000, 1488990.000000
572760.000000, 1488990.000000
572730.000000, 1488990.000000
572700.000000, 1488990.000000
572580.000000, 1488990.000000
572550.000000, 1488990.000000
572520.000000, 1488990.000000
572490.000000, 1488960.000000
572790.000000, 1488990.000000
572760.000000, 1488990.000000
572730.000000, 1488990.000000
572490.000000, 1488960.000000
572460.000000, 1488960.000000
572820.000000, 1488990.000000
572790.000000, 1488990.000000
572760.000000, 1488990.000000
572490.000000, 1488960.000000
572460.000000, 1488960.000000
572430.000000, 1488960.000000
572400.000000, 1488930.000000
572850.000000, 1488990.000000
572820.000000, 1488990.000000
572790.000000, 1488990.000000
572400.000000, 1488930.000000
572370.000000, 1488930.000000
572880.000000, 1488990.000000
572850.000000, 1488990.000000
572820.000000, 1488990.000000
572400.000000, 1488930.000000
572370.000000, 1488930.000000
572340.000000, 1488930.000000
572910.000000, 1488990.000000
572880.000000, 1488990.000000
572850.000000, 1488990.000000
572310.000000, 1488900.000000
572940.000000, 1488990.000000
572910.000000, 1488990.000000
572880.000000, 1488990.000000
572310.000000, 1488900.000000
572280.000000, 1488900.000000
572970.000000, 1488990.000000
572940.000000, 1488990.000000
572910.000000, 1488990.000000
572310.000000, 1488900.000000
572280.000000, 1488900.000000
572250.000000, 1488900.000000
573000.000000, 1488990.000000
572970.000000, 1488990.000000
572940.000000, 1488990.000000
572280.000000, 1488900.000000
572250.000000, 1488900.000000
572220.000000, 1488900.000000
572220.000000, 1488870.000000
572220.000000, 1488870.000000
573030.000000, 1488990.000000
573000.000000, 1488990.000000
572970.000000, 1488990.000000
572220.000000, 1488870.000000
572190.000000, 1488870.000000
573060.000000, 1488990.000000
573030.000000, 1488990.000000
573000.000000, 1488990.000000
572220.000000, 1488870.000000
572190.000000, 1488870.000000
572160.000000, 1488870.000000
572130.000000, 1488840.000000
572130.000000, 1488840.000000
572100.000000, 1488840.000000
572130.000000, 1488840.000000
572100.000000, 1488840.000000
572070.000000, 1488840.000000
572100.000000, 1488840.000000
572070.000000, 1488840.000000
572040.000000, 1488840.000000
572070.000000, 1488840.000000
572040.000000, 1488840.000000
572010.000000, 1488840.000000
572040.000000, 1488840.000000
572010.000000, 1488840.000000
571980.000000, 1488840.000000
572010.000000, 1488840.000000
571980.000000, 1488840.000000
571950.000000, 1488840.000000
571980.000000, 1488840.000000
571950.000000, 1488840.000000
571920.000000, 1488840.000000
```

**Comment by dtarb** [comment] 2017-01-17 02:37
That upwacoor.txt file is identical to the one I get and the correct upstream watershed is being identified, so for me this removes it from suspicion as related to the problem.  I think the problem lies with the ogr2ogr commands. The first ogr2ogr command is conceptually simple, appending, while the second one at line 203 is harder as it involves identifying line segments to remove based on spatial overlaps.  Somehow I think that this function is requiring more computational memory than the process doing it has and that is causing it to fail sometimes.  

The fact that it appears to complete sometimes is puzzling.  Why does it print watershed attributes time, but then report that there is an error in the Point_WaterShed_function.  The only place left to go wrong is the clean up code deleting intermediate files.  Perhaps a process has failed and still has a lock on an intermediate file.

I would next look at the shapefiles left behind before the purge and remove lines and see if they are complete, bu trying to visualize in a GIS.  If you want to send them to me I can take a look.  If there is a way to up the memory for the process running the ogr2ogr and shape to JSON functions I would try that too.

**Comment by kdeloach** [comment] 2017-01-17 15:29
Good idea. I'll analyze the generated shapefiles and send you a sample. I can also investigate increasing resources.

**Comment by kdeloach** [comment] 2017-01-17 18:15
All signs point to memory allocations errors due to insufficient resources. The New_Point_Watershed shapefile produced from RWD on our end matches your output exactly. However, the shape is so complex that we are unable to convert it to GeoJSON. Matt will follow up with more details.

**Closed** 2017-01-26 21:15 UTC
Labels: NSF
