### ISSUE TITLE
Add more descriptive title to water quality tab

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1547] opened 2016-10-19 12:52 UTC
Suggestion from Stroud: "Average Annual Loading Rates/Stream Concentrations"

Tagging @jfrankl for placement, given upcoming UI update

**Comment by mmcfarland** [comment] 2016-10-20 16:36
Duplicate of #1541

**Comment by kellyi** [comment] 2016-10-20 20:16
Shares a point with #1552

**Closed** 2016-11-03 20:30 UTC
