### ISSUE TITLE
Select by boundary picks incorrect boundaries

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#3082] opened 2019-02-04 23:17 UTC
The select by boundary tool does not appear to be working.  It seems to be selecting the boundaries from previous locations or zoom levels.  The hover tip gives the wrong area name.  Clicking in the area with the incorrect hover tip takes you to the area that matches the name, not the area you are hovered over.

To reproduce:
select boundary - pick any, they all seem to be wrong
move mouse around over region - look for any inconsistencies
jump to any other location using the search bar
move mouse  around over region again- see more inconsistencies
click on a suspicious boundary name
be teleported to that boundary

Some MD school district in Coatesville, PA:
![image](https://user-images.githubusercontent.com/5374350/52243548-04b37f80-28a8-11e9-82ac-ea8f8f79b6c6.png)
The Hudson river HUC in Philly:
![image](https://user-images.githubusercontent.com/5374350/52243775-b652b080-28a8-11e9-857d-c0ecb3e54ff9.png)
LA county in central Missouri:
![image](https://user-images.githubusercontent.com/5374350/52243873-13e6fd00-28a9-11e9-9cb0-118e85b4f5d6.png)

**Comment by rajadain** [comment] 2019-02-18 18:15
Hi Sara, I just started taking a look at this. I do see the errors if I enable a boundary, then zoom out and back in to another part of the country. I also see it if I enable a boundary, then search for a new location and try there. If I load the boundaries after selecting my viewing area, they work correctly.

Are any of the examples above of the boundaries being mistaken on a fresh load / moving the map _first_ and selecting a boundary _second_? I haven't been able to reproduce that, and would appreciate any direction you could point me towards.

**Comment by SRGDamia1** [comment] 2019-02-18 20:43
I have it happen on a fresh load as soon as I open the app.

**Comment by rajadain** [comment] 2019-02-18 22:30
Thanks for confirming, Sara. I've so far been unable to reproduce that:

![2019-02-18 17 28 58](https://user-images.githubusercontent.com/1430060/52979265-d1421c00-33a2-11e9-96e2-85aa1fcf2b7c.gif)

but will keep trying.

**Comment by rajadain** [comment] 2019-07-08 15:14
Hi @SRGDamia1, we've fixed this issue and deployed it on Staging: https://staging.modelmywatershed.org/. Could you please take a look there when you get the chance and let us know if it now works as it should? Thank you.

**Comment by SRGDamia1** [comment] 2019-07-08 15:36
It's looking good to me.

There is some lag when I change the boundary type, switch locations via search, or select a region - the map takes a few seconds to redraw - but all of the boundary tool-tips and the actual boundary selected seem to be correct.

**Comment by rajadain** [comment] 2019-07-08 15:39
Thanks for taking a look!

> the map takes a few seconds to redraw

We've upgraded the underlying tile generation infrastructure in #3091, which will need new tiles to be generated and cached. Once enough new tiles are cached, the switching should be much faster. But I'll take a look at that and make sure there's no other reason.

**Comment by SRGDamia1** [comment] 2019-07-08 15:49
Great.  I was guessing the slowness was related to caching or the fact that it's the staging server.

**Comment by rajadain** [comment] 2019-07-25 19:44
Fixed in #3091.

**Closed by rajadain** 2019-07-25 19:44 UTC
Labels: bug, production
