### ISSUE TITLE
Geoprocessing division error

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#811] opened 2015-09-18 19:21 UTC
Running a sq km AoI as seen below resulted in the following error reported from my `debugcelery` window.  Note some values are still reported.  Drawing very similar AoIs don't always reproduce this error and I failed to save the exact geometry of the AoI :disappointed: 

We should try to protect against doing calculations when `count` is 0.

![screenshot from 2015-09-18 15 17 55](https://cloud.githubusercontent.com/assets/1014341/9968788/784c9958-5e18-11e5-89a3-2cecdc82312d.png)

Error:
```bash
[2015-09-18 15:14:34,596: ERROR/MainProcess] Task apps.modeling.tasks.run_analyze[288065ed-c629-4192-8b00-91a1f7348199] raised unexpected: ZeroDivisionError('float division by zero',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 42, in run_analyze
    results = geojson_to_survey(area_of_interest)
  File "/opt/app/apps/modeling/geoprocessing.py", line 224, in geojson_to_survey
    return data_to_survey(data)
  File "/opt/app/apps/modeling/geoprocessing.py", line 214, in data_to_survey
    return histogram_to_x(data, nucleus, update_rule, after_rule)
  File "/opt/app/apps/modeling/geoprocessing.py", line 97, in histogram_to_x
    after_rule(total, retval)
  File "/opt/app/apps/modeling/geoprocessing.py", line 198, in after_rule
    survey[0]['categories'] = [update_pcts(v, count) for k, v in land]
  File "/opt/app/apps/modeling/geoprocessing.py", line 168, in update_pcts
    entry['coverage'] = float(area) / count
ZeroDivisionError: float division by zero
```

**Comment by caseypt** [comment] 2015-09-21 16:33
I can reproduce this consistently with the following AoI (working on getting my host to be shareable):

![screen shot 2015-09-21 at 11 24 34 am](https://cloud.githubusercontent.com/assets/1042475/9997663/6d260100-605b-11e5-8164-8ec04f2e144b.png)

This is caused by bad results from the geoprocessing service. If you make a quick fix for this error ...

```
     def update_pcts(entry, count):
         area = entry['area']
-        entry['coverage'] = float(area) / count
+       print(entry)
+        try:
+            entry['coverage'] = float(area) / count
+        except:
+            entry['coverage'] = 0
         return entry
```

... you will see that the census is all zeros. You'll probably need to also increase the client-side timeout from 10s to 20s.

```
[2015-09-21 12:29:16,937: WARNING/Worker-1] {u'type': u'Woody Wetlands', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,937: WARNING/Worker-1] {u'type': u'Developed, Low Intensity', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,937: WARNING/Worker-1] {u'type': u'Barren Land (Rock/Sand/Clay)', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,937: WARNING/Worker-1] {u'type': u'Open Water', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,942: WARNING/Worker-1] {u'type': u'Emergent Herbaceous Wetlands', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,948: WARNING/Worker-1] {u'type': u'Deciduous Forest', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,960: WARNING/Worker-1] {u'type': u'Developed, Medium Intensity', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,963: WARNING/Worker-1] {u'type': u'Mixed Forest', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,971: WARNING/Worker-1] {u'type': u'Perennial Ice/Snow', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,974: WARNING/Worker-1] {u'type': u'Developed, High Intensity', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,976: WARNING/Worker-1] {u'type': u'Shrub/Scrub', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,981: WARNING/Worker-1] {u'type': u'Evergreen Forest', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,989: WARNING/Worker-1] {u'type': u'Grassland/Herbaceous', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,990: WARNING/Worker-1] {u'type': u'Cultivated Crops', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,991: WARNING/Worker-1] {u'type': u'Developed, Open Space', u'coverage': None, u'area': 0}
[2015-09-21 12:29:16,993: WARNING/Worker-1] {u'type': u'Pasture/Hay', u'coverage': None, u'area': 0}
```

Also of note is that this usually happens after the call to `geoprocessing.histogram` has taken 10s, which may indicate that another timeout is being hit.

```
[2015-09-21 12:29:06,857: WARNING/Worker-1] geojson_to_survey
[2015-09-21 12:29:06,864: WARNING/Worker-1] json_polygon
[2015-09-21 12:29:06,891: WARNING/Worker-1] histogram
[2015-09-21 12:29:16,936: WARNING/Worker-1] data_to_survey
[2015-09-21 12:29:16,936: WARNING/Worker-1] histogram_to_x
...
```

**Comment by caseypt** [comment] 2015-09-21 20:44
I think this error is hard to reproduce for small AoIs is because the timing is largely dependent on the network speed. Most of the time running the analyze or modeling tasks seems to be in getting tiles from S3. In my tests, running models on large AoIs (half of PA, for example) almost always fail because of timeout issues. For smaller areas, the tasks don't fail as often, but when they do fail, it seems to because we were still fetching tiles from S3 (and the fetches were slow) before the 10s SJS/Akka timeout hit.

**Comment by jamesmcclain** [comment] 2015-09-23 15:25
As @lliss observed somewhere else, this error can be reliably reproduced by doing the following:
   * Selecting a huge AoI which is doomed to failure because it cannot download the tiles that it needs within the time limit.
   * Selecting another AoI, meanwhile the Scala process servicing the first AoI is still going.  The process to service the second AoI will be starved and will fail.

#823 will hopefully fix the starvation issue, but not the lots-of-tiles issue.

**Comment by mmcfarland** [comment] 2015-10-22 18:56
I think this is resolved - right?

**Comment by jamesmcclain** [comment] 2015-10-22 19:33
Yes, we now terminate jobs which are taking too long, so the starvation problem from before should be less of an issue.  The too-many-tiles issues has (kind of) been addressed by limiting the AoI size.

**Closed** 2016-07-19 15:34 UTC
Labels: bug
