### ISSUE TITLE
Compare View Revamp: Loading / Error Displays

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2099] opened 2017-07-28 20:58 UTC
How should it look when scenarios are still being processed? They are all processed independently, so we can get results in any order (i.e. scenarios to the right may get results first while those on the left may still be spinning).

How do we show scenarios that have errored out?

Once we have mockups for this, implement them.

**Comment by rajadain** [comment] 2017-07-28 20:59
I've tagged @jfrankl to provide mockups. Once we have them, a developer should do the actual implementation.

**Comment by jfrankl** [comment] 2017-08-23 20:26
Duplicate of #2134

**Closed by jfrankl** 2017-08-23 20:26 UTC
Labels: design, WPF
