### ISSUE TITLE
Navigating away from search does not clear map elements

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2082] opened 2017-07-25 13:31 UTC
When a data catalog search has been executed and there are features added to the map, they are not removed when navigating away from the search page.

To reproduce:
1. Execute a search and ensure geometries are visible on the map
2. Click the logo-text "Critical Zone Data Explorer" in the header

![screenshot from 2017-07-25 09 29 06](https://user-images.githubusercontent.com/1014341/28574402-e50b8956-711b-11e7-9d98-c2bdaade8e4f.png)

**Comment by arottersman** [comment] 2017-07-25 15:58
Somewhat a duplicate of #2054

**Closed** 2017-07-25 16:33 UTC
Labels: BigCZ, bug
