### ISSUE TITLE
Drawing twice creates empty space in footer

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#893] opened 2015-09-30 14:59 UTC
1 Draw an area

2 Click back button

![image](https://cloud.githubusercontent.com/assets/43062/10196622/cf49b8f6-6761-11e5-9f92-ed9708a70430.png)

3 Draw area

![image](https://cloud.githubusercontent.com/assets/43062/10196658/ecf53434-6761-11e5-85b1-c58ff115721c.png)

There's a big empty space where the footer used to be.

Source: mmw.azavea.com version ccdf9d75de0fa44435e37a92e64b51546864b0ae.

**Comment by mmcfarland** [comment] 2015-09-30 15:03
Duplicate of #883

**Comment by kdeloach** [comment] 2015-10-08 19:04
Not a duplicate and still observable on staging.

**Closed** 2015-10-16 13:35 UTC
