### ISSUE TITLE
Firefox has problem snapshotting "Satellite with Roads" basemap

### ISSUE THREAD

**Issue by scytacki** [WikiWatershed/model-my-watershed#1640] opened 2016-12-09 17:55 UTC
To reproduce
1. In Firefox, log into the [ITSI portal](https://itsi.portal.concord.org)
2. Then open this URL: https://authoring.concord.org/activities/5644
3. Scroll down until you see the MMW interactive.
4. Click the interactive to open it
5. Change the Basemap to "Satellite with Roads"
6. Draw a Square Km Area
7. Take a snapshot (in the top right)

You should see something like:
![screen shot 2016-12-09 at 12 51 02 pm](https://cloud.githubusercontent.com/assets/86016/21058926/3233d9e8-be0e-11e6-835c-1e9c20df4f37.png)

Look at the image in the Editing Snapshot window.  Notice the bulleted list at the top and the grey area on the right.
If the Basemap is set to "Streets" this doesn't happen. If the Basemap is set to "Streets" and then set back to "Satellite with Roads" then problem goes away.

So this might be the same issue as #1639

**Comment by ajrobbins** [comment] 2016-12-20 21:46
Shares points with #1639

**Comment by rajadain** [comment] 2016-12-27 18:56
After some investigation, this is where I am:

I can reproduce this issue by taking a screenshot upon immediate load. The screenshot looks like this:

![image](https://cloud.githubusercontent.com/assets/1430060/21506093/83933460-cc3b-11e6-8156-baabfa268b32.png)

if I open the layer selector and switch to "Satellite" and back to "Streets", the screenshot looks like this:

![image](https://cloud.githubusercontent.com/assets/1430060/21506100/98f2f39a-cc3b-11e6-91c3-d53e2c3ddcfd.png)

These are the respective HTML shutterbug caches of these images: https://ccshutterbugtest.s3.amazonaws.com/347c0facfab.html and https://ccshutterbugtest.s3.amazonaws.com/bfdfd609401.html. (Interestingly neither page opens correctly in Firefox, but both do in Chrome).

If I run PhantomJS with [rasterize.js](https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js) on these HTML pages locally, I get two correctly rendered images:

![firefox-before-347c0facfab](https://cloud.githubusercontent.com/assets/1430060/21506139/d8ccf286-cc3b-11e6-97a4-2a8993f9e30a.png)

![firefox-after-bfdfd609401](https://cloud.githubusercontent.com/assets/1430060/21506144/de07062e-cc3b-11e6-8e52-fd8eb25b6890.png)

The diff between the two HTML files seems innocent, and nothing stands out so far.

Going to cycle back to this in a little while.

**Comment by rajadain** [comment] 2016-12-28 16:58
Clicking the layer selector adds a `#` to the end of the URL, that for some reason makes the screenshots work for Firefox.

Trying the following command:

```bash
$ curl 'https://snapshot.concord.org/shutterbug/make_snapshot' \
    --compressed \
    -H 'Host: snapshot.concord.org' \
    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0' \
    -H 'Accept: */*' \
    -H 'Accept-Language: en-US,en;q=0.5' \
    -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
    -H 'Referer: https://authoring.concord.org/activities/5644/single_page/22114431-c5e3-4ed7-bb5a-71a196d5ee51' \
    -H 'Origin: https://authoring.concord.org' \
    -H 'DNT: 1' \
    -H 'Connection: keep-alive' \
    --data @firefox-bad-screenshot.data.txt
```

with the following files:

 * [firefox-bad-screenshot.data.txt](https://github.com/WikiWatershed/model-my-watershed/files/675909/firefox-bad-screenshot.data.txt)
 * [firefox-bad-screenshot.data.fixed.txt](https://github.com/WikiWatershed/model-my-watershed/files/675910/firefox-bad-screenshot.data.fixed.txt)

The only difference between them is `%23` in line 1 col 632. The first produces an erring screenshot:

![image](https://cloud.githubusercontent.com/assets/1430060/21526765/9ea37d82-ccf4-11e6-87d8-c5213172183e.png)

the second produces the correct screenshot:

![image](https://cloud.githubusercontent.com/assets/1430060/21526777/ae9c1e9c-ccf4-11e6-966b-9c03a3f4b498.png)

I will now compare this with what something like Chrome sends to see if I can explain why the presence of `%23` fixes this, and what the solution should be.

**Comment by rajadain** [comment] 2016-12-28 17:48
Chrome HTML encodes the data before URL encoding it. If we take [firefox-bad-screenshot.data.txt](https://github.com/WikiWatershed/model-my-watershed/files/675909/firefox-bad-screenshot.data.txt) from above and HTML encode `<`, `>`, and `\n` to `&lt;`, `&gt;`, and `&#10;` respectively in [firefox-bad-screenshot.data.fixed-html-encoding.txt](https://github.com/WikiWatershed/model-my-watershed/files/675987/firefox-bad-screenshot.data.fixed-html-encoding.txt), and POST that:

```bash
$ curl 'https://snapshot.concord.org/shutterbug/make_snapshot' \
    --compressed \
    -H 'Host: snapshot.concord.org' \
    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0' \
    -H 'Accept: */*' \
    -H 'Accept-Language: en-US,en;q=0.5' \
    -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
    -H 'Referer: https://authoring.concord.org/activities/5644/single_page/22114431-c5e3-4ed7-bb5a-71a196d5ee51' \
    -H 'Origin: https://authoring.concord.org' \
    -H 'DNT: 1' \
    -H 'Connection: keep-alive' \
    --data @firefox-bad-screenshot.data.fixed-html-encoding.txt
```

we get the correct screenshot:

![image](https://cloud.githubusercontent.com/assets/1430060/21527792/b84f70c2-ccfb-11e6-8452-978ba5709a59.png)

Note that this does not have the `#` in the URL, but still works correctly.

I am now investigating if we can get Firefox to HTML encode the payload before sending it.

**Comment by rajadain** [comment] 2016-12-28 20:46
I've discovered that jQuery's `.html()`, used here in the Shutterbug code: https://github.com/concord-consortium/shutterbug.js/blob/d3a25de12b0c4ac6a673ee7a356a81a12609b106/app/scripts/shutterbug-worker.js#L156, returns non-HTML encoded value in Firefox, and an encoded value in Chrome.  If it uses [`innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) under the hood, it _should_ return HTML encoded values according to the spec. Taking a peek at that now.

**Comment by rajadain** [comment] 2016-12-28 21:53
Proceeding on that line of inquiry, I've found that `.innerHTML` or `outerHTML` in Firefox don't escape the contents of an attribute, _even when the contents were originally escaped_. See example in Firefox:

![image](https://cloud.githubusercontent.com/assets/1430060/21532375/7816f896-cd1d-11e6-8788-9538cec7e3d7.png)

Chrome behaves in the opposite manner, escaping the encoding in the console output, but preserving it in the string representation:

![image](https://cloud.githubusercontent.com/assets/1430060/21532410/d5dc53fe-cd1d-11e6-8701-692780d7c1c4.png)

![image](https://cloud.githubusercontent.com/assets/1430060/21532415/e3c9eeae-cd1d-11e6-8e70-616b79c71a6e.png)

![image](https://cloud.githubusercontent.com/assets/1430060/21532418/f1be3d08-cd1d-11e6-8ec8-41cc60a4f097.png)

I can find little explanation of these conventions, but they seem to be playing a part here.

**Comment by rajadain** [comment] 2016-12-28 21:55
On the other hand, for the `#` behavior, Shutterbug has had to deal with it before: https://github.com/concord-consortium/shutterbug/commit/a203755475b32144b775d3de8d5306bc6a2bb9e1. Perhaps this can be addressed on that end, @scytacki?

**Comment by rajadain** [comment] 2016-12-28 23:20
I tried to change the Shutterbug.js code used in MMW (since we use a shim) to always append a hash in the URL, but I think the Shutterbug.js that executes at runtime is on your side, not ours. I've created a PR on Shutterbug.js https://github.com/concord-consortium/shutterbug.js/pull/4 that addresses this. @scytacki, if you can get that reviewed, merged, and deployed, we may be able to fix this.

**Comment by rajadain** [comment] 2016-12-29 19:57
Ended up adding a `#` to the URL in the `saycheese` event, which we could do completely on our side.

concord-consortium/shutterbug.js#4 is not needed by us anymore, but might be useful to others using Shutterbug.js. I can close it if you want.

**Closed** 2017-01-03 20:35 UTC
Labels: ITSI Portal, NSF
