### ISSUE TITLE
investigate node-sass issue

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#195] opened 2015-05-21 12:57 UTC
I've bumped the version of node-sass to 3.1.1 because the old version stopped working for me -- it would not update main.css when I would change one of the sass files. This is strange since it seemed to work before. The new version works well so far, except that it causes the bundle script to crash when the watch flag is set and a change is made to a sass file. My interim solution is to just kill the bundle script and run it without the watch flag when I make a change to a sass file.

We should figure out how to fix this more properly.

**Comment by kdeloach** [comment] 2015-05-22 18:22
May be related, but whenever I switch branches with `--watch` enabled this happens:
```
=> changed: /opt/app/sass/main.scss
=> changed: /opt/app/sass/main.scss
=> changed: /opt/app/sass/main.scss
=> changed: /opt/app/sass/main.scss
=> changed: /opt/app/sass/main.scss
=> changed: /opt/app/sass/main.scss
=> changed: /opt/app/sass/main.scss
=> changed: /opt/app/sass/main.scss
./bundle.sh: line 144: 12240 Killed                  ./node_modules/.bin/watchify --debug ./js/src/**/tests.js -t [ jstify --noMinify ] -o /var/www/mmw/static/js/test.bundle.js --verbose --poll
=> changed: /opt/app/sass/main.scss
Connection to 127.0.0.1 closed.
> 
```

**Comment by mmcfarland** [comment] 2015-05-27 20:13
May be made obsolete by #217

**Comment by kdeloach** [comment] 2015-05-27 20:19
I have not had this issue since I started using #217 but that could be a coincidence. I scarcely modify sass files.

**Comment by kdeloach** [comment] 2015-05-28 17:24
@lewfish Mind verifying if this is still an issue or not on the latest develop?

**Comment by lewfish** [comment] 2015-05-28 17:35
The problem only occurs intermittently, but I'll try my best to trigger a meltdown.

**Comment by lewfish** [comment] 2015-05-29 14:42
@kdeloach I made a bunch of changes to a sass file within a short amount of time and there wasn't any problem. I think it's fixed.

**Comment by kdeloach** [comment] 2015-05-29 15:09
I think the main cause is the VM running out of memory. I was able to reproduce this issue by running `reload_dev_data` with the watch active. Closing since there are workarounds and the problem is not as prevalent as before.

**Closed by kdeloach** 2015-05-29 15:09 UTC
Labels: queue
