### ISSUE TITLE
Analyze csv's from HydroShare export do not match downloads from Analyze

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2669] opened 2018-02-20 19:25 UTC
The csv file names and column names are different, and there are some additional columns in the HydroShare export. We should match the Analyze csv schemas exactly in the HS export.

Original implementation https://github.com/WikiWatershed/model-my-watershed/commit/7b2b1125d158f7287c81ac6e497c5141f7aa1052

**Comment by rajadain** [comment] 2018-02-20 19:32
Possibly duplicate of https://github.com/WikiWatershed/model-my-watershed/issues/2575.

To clarify: the HydroShare export should be changed to match the downloads, not the other way, correct?

**Comment by ajrobbins** [comment] 2018-02-20 19:33
Yes, and it is a dupe. Closing in facor of #2575

**Closed** 2018-02-20 19:37 UTC
Labels: HydroShare Export, WPF, in progress
