### ISSUE TITLE
GeoP deploy support

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#785] opened 2015-09-10 20:00 UTC

**Comment by mmcfarland** [comment] 2015-09-15 21:32
I think we should use this card to start investigating why some model runs are failing.

**Comment by caseypt** [comment] 2015-09-22 13:14
## Failing geoprocessing jobs

While testing out why some analyze and modeling jobs were failing, I noticed that most jobs for small (~1km) AoIs succeeded, but as the AoI grows, so does the rate of failure.

The quickest solution to getting more jobs to succeed was to increase the client-side polling timeout. It is currently set at 10s. Increasing it to 20s allowed a lot of jobs for neighborhood-sized and larger AoIs to succeed. Currently, there is a 10s timeout for the core geoprocessing tasks. I think our client-side timeout should be set a few seconds more than this to account for the processing time (1 or 2s) before and after the geoprocessing task, while also giving time for longer geoprocessing tasks (just less than 10s) to finish.

Geoprocessing tasks that are hitting the geoprocessing timeout are the cause of the [division by zero error](https://github.com/WikiWatershed/model-my-watershed/issues/811#issue-107262190). There's more information [here](https://github.com/WikiWatershed/model-my-watershed/issues/811#issuecomment-142036211), but here's the response from Spark Job Server:

```
[2015-09-21 16:37:34,411: WARNING/Worker-1] {u'status': u'ERROR', u'result': {u'errorClass': u'akka.pattern.AskTimeoutException', u'message': u'Ask timed out on [Actor[akka://JobServer/user/context-supervisor/geoprocessing#-288271378]] after [10000 ms]', u'stack': [u'akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)', u'akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)', u'scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)', u'scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)', u'akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)', u'akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)', u'akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)', u'akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)', u'java.lang.Thread.run(Thread.java:745)']}}
```

The majority of the geoprocessing task run time is taken up by fetching tiles from S3. For very large AoIs (like half the state of PA), the task is still fetching tiles when the timeout hits. It should be noted that the geoprocessing job continues, even though the results will never make it back to the client-side. Also, on very large jobs, SJS writes some of the tile data to disk if there isn't enough memory avialable. When this happens, the job response time is even longer. A sample from the SJS logs:

```
writing to disk Thread 143 spilling in-memory map of 646.9 MB to disk (1 time so far)
```

@jamesmcclain has proposed two fixes to the issues described above. 

The first is to make the SJS job itself async, and poll for results from Django/Celery. This will remove the 10s geoprocessing timeout, but it adds some complexities because it would introduce an async process to the Celery chain. It also opens up the question of how long we should be waiting for these jobs to complete.

The other potential solution is to precompute histograms tile groups, as proposed [here](https://github.com/WikiWatershed/mmw-geoprocessing/issues/5), but this introduces other complexities that @jamesmcclain and @hectcastro have a better handle on.

I also created https://github.com/WikiWatershed/model-my-watershed/issues/818 and https://github.com/WikiWatershed/model-my-watershed/issues/815 to improve the UX/UI of failing tasks.

**Comment by jamesmcclain** [comment] 2015-09-22 13:29
I am working on making the SJS job asynchronous.  Hopefully it will not be too bad, but I may need to ask a few celery questions at some point today.

**Comment by hectcastro** [comment] 2015-09-22 14:39
I added some additional logging that may be useful when working on the geoprocessing workflow in https://github.com/WikiWatershed/model-my-watershed/pull/824.

**Comment by kdeloach** [comment] 2015-11-05 20:50
Can we close this?

**Closed** 2015-11-05 21:43 UTC
