### ISSUE TITLE
MapShed "Add changes to this area button" not shown when user is logged in

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#2298] opened 2017-09-26 17:00 UTC
The MapShed "Add changes to this area" button currently only shows up when the user is not logged in to the app.

If an aoi is modeled while the user is not logged in, the button will appear.

Once the user logs in, the button disappears at almost the same moment the project url goes from `/project/` to `/project/94/scenario/268` or similar.

**Comment by caseycesari** [comment] 2017-10-03 15:41
I'm not able to fix this because MapShed will not complete locally for me, but I know what the issue is.

The problem is the [gis_data](https://github.com/WikiWatershed/model-my-watershed/blob/2b17268dc31e6dd07e50c4d8b1cf349ca6fb0a1b/src/mmw/js/src/modeling/templates/gmsDownloadForm.html#L5) variable that contains the output for the GMS export contains quotes and becomes incorrectly escaped:

<img width="471" alt="screen shot 2017-10-03 at 11 25 02 am" src="https://user-images.githubusercontent.com/1042475/31134242-8c851a9a-a82f-11e7-95cf-9f2013ff3088.png">

*It looks like it's incorrectly escaped from the beginning*

<img width="522" alt="screen shot 2017-10-03 at 11 24 38 am" src="https://user-images.githubusercontent.com/1042475/31134241-8c83bdd0-a82f-11e7-8dbb-15da1d068108.png">

*You can see the browser is trying to parse the data into HTML elements*

**Comment by arottersman** [comment] 2017-10-04 13:57
This was fixed by https://github.com/WikiWatershed/model-my-watershed/pull/2309, but we hadn't run migrations yet. I've just run them. @caseycesari mind taking a quick look on staging and confirming the issue has been resolved?

**Comment by caseycesari** [comment] 2017-10-04 14:16
Confirmed! It's fixed.

**Closed** 2017-10-05 20:38 UTC
Labels: bug, WPF
